### ISSUE TITLE
Kill the `-js`

### ISSUE THREAD

**Issue by timoxley** [paldepind/union-type-js#8]
https://www.npmjs.com/package/union-type is available :D

**Comment by davidchambers** [comment]
Good idea!

**Comment by paldepind** [comment]
Yes. That certainly looks better :)

**Comment by davidchambers** [comment]
You should update the repository name to match. :)

**Comment by timoxley** [comment]
@paldepind you probably also want to deprecate https://www.npmjs.com/package/union-type-js

**Comment by paldepind** [comment]
@timoxley I actually did. The npm page shows nothing but there is a warning if one installs `union-type-js`.
